import { useEffect } from "react";
import MediaGallery from "./MediaGallery";
import { projectBySlug } from "./project-data";

const featured = [
  { title: "6-DOF Robot Arm", kicker: "Current project · Robotics", image: "/media/cycloidal-drive/1cycloidv3.jpg", href: "/projects/robot-arm", wide: true, description: "A six-axis arm built around custom cycloidal joint drives, stepper control, and iterative FDM prototypes.", tags: ["SolidWorks", "Arduino", "Mechanism Design"] },
  { title: "Cycloidal Drive", kicker: "21:1 reduction · Gearbox design", image: "/media/cycloidal-drive/2cycloidv3.jpg", href: "/projects/cycloidal-drive", description: "Compact, low-backlash gearboxes designed from scratch for every joint of the robot arm.", tags: ["Equation-driven CAD", "FDM", "Prototyping"] },
  { title: "Star Wars Marble Run", kicker: "Mechanism design", image: "/media/marble-run/marble1.jpg", href: "/projects/marble-run", description: "A 600 mm dual-path machine with a powered elevator, launcher, and nearly 5 kg of printed parts.", tags: ["SolidWorks", "Arduino", "Team Project"] },
  { title: "Wind-Up Mouse Droid", kicker: "Spring-powered drivetrain", image: "/media/mouse-droid/wind0.jpg", href: "/projects/mouse-droid", description: "A functional PETG model powered by a custom ratchet, torsion spring, and manually designed gear train.", tags: ["Gear Design", "DFAM", "PETG"] },
  { title: "Filament Recycler Spool Holder", kicker: "FabLab · Production tooling", image: "/media/filament-spool-holder/filabot3.jpg", href: "/projects/filament-spool-holder", description: "A replacement attachment that made generic spools work reliably with the FabLab’s Filabot system.", tags: ["Reverse Engineering", "PETG", "Iteration"] },
  { title: "1981 Yamaha Virago Rebuild", kicker: "Mechanical troubleshooting", image: "/media/virago-rebuild/virago1.jpg", href: "/projects/virago-rebuild", description: "Rebuilt a non-running motorcycle through electrical diagnosis, carburetor repair, and starter redesign.", tags: ["Diagnostics", "Electrical", "Engines"] },
];

const experience = [
  { company: "University of Vermont FabLab", role: "Operations Manager", date: "Jan 2026 — Present", bullets: ["Lead daily operations and provide technical direction for a university fabrication lab supporting coursework, research, and student projects.", "Coordinate technicians, preventive maintenance, scheduling, SOP development, staff meetings, and hiring while remaining hands-on with equipment and troubleshooting.", "Promoted from FabLab Technician after one semester; completed more than 600 fabrication tickets during the first semester."] },
  { company: "Preci Manufacturing", role: "CNC Machinist Intern", date: "Summer 2026", bullets: ["Worked across CNC turning, 5-axis milling, and quality control in a precision aerospace and defense manufacturing environment.", "Performed machine setup, operation, and continuous part inspection to maintain tolerances as tight as ±0.0001 inch.", "Conducted batch inspections and assisted with first-off inspection using drawings, GD&T, CMMs, optical comparators, Micro-Hites, vision systems, and precision gaging.", "Assisted with machine automation setup by verifying workholding, gripper operation, part handling, and process repeatability."] },
  { company: "VEX Robotics · Team 4886", role: "Team Captain and Coach", date: "2017 — 2024", bullets: ["Designed, fabricated, assembled, and iteratively improved competition robot systems under strict time and rules constraints.", "Qualified for the VEX World Championship four times and contributed to the 2023 NH/VT State Championship-winning robot.", "Returned after graduation to coach students in CAD, fabrication, assembly, design documentation, and competition troubleshooting."] },
];

function Header({ project = false }: { project?: boolean }) {
  return <header><nav aria-label="Primary navigation"><a className="brand" href="/">Isaiah Kol</a><div className="nav-links"><a href="/#projects">{project ? "All projects" : "Projects"}</a>{!project && <><a href="/#experience">Experience</a><a href="/#about">About</a></>}<a href="/resume">Résumé</a>{project && <a href="mailto:isaiahkol37@gmail.com">Contact</a>}</div></nav></header>;
}

function Home() {
  return <main id="top"><Header />
    <section className="intro"><div className="intro-copy"><p className="label">Mechanical Engineering · University of Vermont · Class of 2028</p><h1>Isaiah Kol</h1><p className="intro-line">I design, build, and troubleshoot mechanical systems—with a focus on <strong>robotics, manufacturing, and rapid prototyping.</strong></p><a className="project-jump" href="#projects">View projects <span>↓</span></a></div><img className="portrait" src="/media/headshot.jpg" alt="Isaiah Kol" /></section>
    <section className="projects" id="projects"><div className="section-title"><div><span>01</span><h2>Projects</h2></div><p>Selected mechanical design and fabrication work</p></div><div className="project-grid">{featured.map((project, index) => <a className={`project-card ${project.wide ? "wide" : ""}`} href={project.href} key={project.title}><div className="image-wrap"><img src={project.image} alt={project.title} /><span className="view">View project ↗</span><span className="number">0{index + 1}</span></div><div className="project-info"><p className="kicker">{project.kicker}</p><h3>{project.title}</h3><p className="description">{project.description}</p><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div></div></a>)}</div></section>
    <section className="experience" id="experience"><div className="section-title"><div><span>02</span><h2>Experience</h2></div><p>The work behind the projects</p></div><div className="experience-list"><article><p className="date">Summer 2026</p><div><h3>CNC Machinist Intern</h3><p>Precision aerospace & defense manufacturing</p></div><p>Machine setup and operation across CNC turning and 5-axis milling, plus batch and first-off inspection using CMMs, optical comparators, Micro-Hites, and precision gaging.</p></article><article><p className="date">2026 — Present</p><div><h3>FabLab Operations Manager</h3><p>University of Vermont</p></div><p>Lead daily lab operations, technician coordination, maintenance, SOP development, and technical support while staying hands-on with fabrication and research projects.</p></article><article><p className="date">2017 — 2024</p><div><h3>Team Captain & Coach</h3><p>VEX Robotics · Team 4886</p></div><p>Four-time World Championship qualifier and 2023 NH/VT State Champion; later coached students in CAD, fabrication, assembly, and competition troubleshooting.</p></article></div></section>
    <section className="about" id="about"><div><p className="label">About</p><h2>About me</h2></div><div><p>I’ve been using CAD and 3D printing on my own equipment since I was about 13. Today, I’m a junior mechanical engineering student at UVM and help run the university FabLab.</p><p>I’m most interested in work where I can move between CAD, manufacturing, inspection, and physical testing—and where a design has to do more than look good on a screen.</p><div className="about-links"><a href="mailto:isaiahkol37@gmail.com">Email me ↗</a><a href="https://www.linkedin.com/in/isaiah-kol/" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div></section>
    <footer><strong>Isaiah Kol</strong><p>Mechanical Engineering · Burlington, Vermont</p><a href="#top">Back to top ↑</a></footer>
  </main>;
}

function ProjectPage({ slug }: { slug: string }) {
  const project = projectBySlug[slug];
  if (!project) return <NotFound />;
  return <main className="detail-page"><Header project /><article><div className="detail-head"><a className="back" href="/#projects">← All projects</a><p className="label">{project.category}</p><h1>{project.title}</h1><p className="detail-summary">{project.summary}</p><p className="detail-date">{project.date}</p></div><MediaGallery items={project.media} /><dl className="facts">{project.facts.map(([term, value]) => <div key={term}><dt>{term}</dt><dd>{value}</dd></div>)}</dl><div className="detail-content"><section><h2>Overview</h2>{project.overview.map(p => <p key={p}>{p}</p>)}</section>{project.sections.map(section => <section key={section.title}><h2>{section.title}</h2>{section.body.map(p => <p key={p}>{p}</p>)}</section>)}</div><section className="tools"><h2>Tools and methods</h2><div>{project.tools.map(tool => <span key={tool}>{tool}</span>)}</div></section><nav className="project-bottom" aria-label="Project footer"><a href="/#projects">← Return to all projects</a><a href="mailto:isaiahkol37@gmail.com">Contact me ↗</a></nav></article></main>;
}

function Resume() {
  return <main className="resume-page"><Header /><article className="resume-sheet"><div className="resume-head"><div><p className="label">Mechanical Engineering</p><h1>Isaiah Kol</h1><p>Junior mechanical engineering student focused on robotics, aerospace, manufacturing, and hands-on product development.</p></div><address><a href="mailto:isaiahkol37@gmail.com">isaiahkol37@gmail.com</a><span>Burlington, Vermont</span><a href="https://www.linkedin.com/in/isaiah-kol/" target="_blank" rel="noreferrer">LinkedIn</a><a href="/">Portfolio</a><button className="print-button" onClick={() => window.print()}>Print / Save PDF</button></address></div>
    <section className="resume-section"><h2>Education</h2><div className="resume-entry"><div><h3>University of Vermont</h3><p>B.S. Mechanical Engineering · Expected 2028</p></div><p className="resume-date">GPA: 3.82</p></div></section>
    <section className="resume-section"><h2>Experience</h2>{experience.map(item => <div className="resume-entry stacked" key={item.company}><div className="entry-heading"><div><h3>{item.role}</h3><p>{item.company}</p></div><p className="resume-date">{item.date}</p></div><ul>{item.bullets.map(bullet => <li key={bullet}>{bullet}</li>)}</ul></div>)}</section>
    <section className="resume-section"><h2>Projects</h2><div className="resume-entry stacked"><div className="entry-heading"><div><h3><a href="/projects/robot-arm">6-DOF Robot Arm</a></h3><p>Independent project</p></div><p className="resume-date">Mar 2026 — Present</p></div><ul><li>Designed and built a six-axis robotic arm using custom 21:1 cycloidal gearboxes, belt reductions, FDM components, and open-loop stepper control.</li><li>Integrated an Arduino Mega, six DM542TE drivers, a 24 V power system, and computer-based multi-axis jog control.</li></ul></div><div className="resume-entry stacked"><div className="entry-heading"><div><h3><a href="/projects/cycloidal-drive">Cycloidal Gearbox</a></h3><p>Independent project</p></div><p className="resume-date">Jan 2026 — Present</p></div><ul><li>Created a compact dual-disc cycloidal reducer from equation-driven geometry and iteratively improved bearings, pins, clearances, support, and assembly.</li></ul></div><div className="resume-entry stacked"><div className="entry-heading"><div><h3><a href="/projects/marble-run">Star Wars Marble Run</a></h3><p>Advanced 3D Drafting</p></div><p className="resume-date">Fall 2025</p></div><ul><li>Designed and fabricated mechanisms for a 600 mm dual-path marble run with an Arduino-controlled elevator and launcher.</li></ul></div></section>
    <section className="resume-section"><h2>Technical Skills</h2><div className="skills-grid"><p><strong>Design:</strong> SolidWorks, assemblies, drawings, GD&T, design for manufacturing, design for additive manufacturing</p><p><strong>Manufacturing:</strong> CNC turning, 5-axis milling, FDM and SLA printing, laser cutting, machine setup, workholding</p><p><strong>Inspection:</strong> CMMs, optical comparators, Micro-Hites, vision systems, micrometers, dial indicators, precision gaging</p><p><strong>Controls:</strong> Arduino, C++, Python, stepper motors and drivers, basic electronics and machine automation</p></div></section></article><footer><strong>Isaiah Kol</strong><a href="/">Return to portfolio</a></footer></main>;
}

function NotFound() { return <main className="not-found"><div><p className="label">404</p><h1>Page not found.</h1><p>The project or page you requested does not exist.</p><a className="project-jump" href="/">Return home →</a></div></main>; }

export default function App() {
  const path = window.location.pathname.replace(/\/+$/, "") || "/";
  useEffect(() => {
    const project = path.startsWith("/projects/") ? projectBySlug[path.split("/")[2]] : undefined;
    document.title = project ? `${project.title} — Isaiah Kol` : path === "/resume" ? "Résumé — Isaiah Kol" : path === "/" ? "Isaiah Kol — Mechanical Engineering Portfolio" : "Page not found — Isaiah Kol";
  }, [path]);
  if (path === "/") return <Home />;
  if (path === "/resume") return <Resume />;
  if (path.startsWith("/projects/")) return <ProjectPage slug={path.split("/")[2]} />;
  return <NotFound />;
}
